#131 - update http
artipie/pypi-adapter pull request #132
Opened 2020-10-12 13:12 UTC by olenagerasimova

Closes #131 
Updated http and used `BasicAuthSlice`

2020-10-12 14:22 UTC, olegmoz requested changes
@olenagerasimova thanks, please see two comments

2020-10-12 14:22 UTC, olegmoz commented on src/main/java/com/artipie/pypi/http/PySlice.java
> +            (user, pswd) -> Optional.of(new Authentication.User("anonymous"))
@olenagerasimova lets use newly added `Authentication.ANONYMOUS` here

2020-10-12 14:22 UTC, olegmoz commented on src/test/java/com/artipie/pypi/http/PySliceITCase.java
> +            (name, pswd) -> Optional.of(new Authentication.User("anonymous"))
@olenagerasimova I'd suggest to release new version of `http` and use `Authentication.ANONYMOUS` here

2020-10-12 16:12 UTC, olenagerasimova commented
@olegmoz thanks, corrected

2020-10-13 06:21 UTC, olegmoz approved these changes
@olenagerasimova thanks, approved

2020-10-13 06:29 UTC, merged

2020-10-13 07:02 UTC, 0crat commented
Job `gh:artipie/pypi-adapter#132` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/50612048-ee4a-4460-87dc-e88d92dedc4f, version: 0.54.5, hash: ${buildNumber} -->