#135 - artifact not found branch
artipie/pypi-adapter pull request #140
Opened 2020-10-21 08:58 UTC by olenagerasimova

Part of #135 
Implemented branch when requested artifact if not found in `SearchSlice`, added corresponding test, updated http and added 
`SearchSlice` to `PySlice`

2020-10-21 12:26 UTC, olegmoz requested changes
@olenagerasimova thanks, please see one comment

2020-10-21 12:26 UTC, olegmoz commented on src/test/java/com/artipie/pypi/http/SearchSliceTest.java
> +    void returnsEmptyXmlWhenArtifactNotFound() {
@olenagerasimova it seems that test name is misleading, it seems that test check the case when artifact is found and not empty XML response is returned

2020-10-21 16:37 UTC, olenagerasimova commented on src/test/java/com/artipie/pypi/http/SearchSliceTest.java
> +    void returnsEmptyXmlWhenArtifactNotFound() {
@olegmoz hm, why? Item in storage is called "some_project" and project name from request is "my_project", so these are different names. I think it will be more obvious if I just leave storage empty 
The thing is, that according to this protocol we have to return OK and some empty xml instead of "NOT FOUND" response status.

2020-10-21 16:52 UTC, olenagerasimova commented
@olegmoz answered and corrected, take a look please

2020-10-22 08:14 UTC, olegmoz commented on src/test/java/com/artipie/pypi/http/SearchSliceTest.java
> +    void returnsEmptyXmlWhenArtifactNotFound() {
@olenagerasimova got it wrong then, sorry. Thanks for correcting to make it more obvious.

2020-10-22 08:14 UTC, olegmoz approved these changes

2020-10-22 08:37 UTC, merged

2020-10-22 09:03 UTC, 0crat commented
Job `gh:artipie/pypi-adapter#140` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/6063c261-baa6-47a6-9519-d56611aba8ad, version: 0.54.5, hash: ${buildNumber} -->