feat: proxy events
artipie/pypi-adapter pull request #184
Opened 2023-08-04 13:09 UTC by olenagerasimova

closes #183
Implemented proxy events queue and job to check packages and them to packages queue. The job itself will be started from artipie/artipie module if packages db is required and configured in repository settings.

2023-08-07 14:11 UTC, dgarus requested changes
Thanks!
Please read my comment

2023-08-07 14:11 UTC, dgarus commented on src/main/java/com/artipie/pypi/PyProxyPackageProcessor.java
> +                            final CompletionStage<Void> res;
Do we really need to create a future here?
We are already in the separate thread, and we want to finish the job here, that is why we call `join()`. So, I think we could just do all work in sync manner.

2023-08-28 07:01 UTC, olenagerasimova commented
@dgarus thanks, corrected

2023-08-29 08:57 UTC, dgarus commented on src/main/java/com/artipie/pypi/http/PySlice.java
> +        this(storage, Policy.FREE, Authentication.ANONYMOUS, "*", Optional.of(new LinkedList<>()));
`LinkedList` is not thread safe collection, but it is changed inside futures. It doesn't look correct.
Do we really need to create a queue here? Can we pass `Optional.empty()`?

2023-08-29 11:11 UTC, dgarus approved these changes
Thanks! lgtm

2023-08-29 11:27 UTC, merged